#!/bin/bash
#SBATCH --job-name=bin_%j
#SBATCH --output=logs/bin_%j.log
#SBATCH --error=logs/bin_%j.err
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=cynthiabecker@ufl.edu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=5gb
#SBATCH --time=4-00:00:00
#SBATCH --account=juliemeyer
#SBATCH --qos=juliemeyer-b

export OMP_NUM_THREADS=20

# Run this script from the blue/juliemeyer/cynthiabecker/ofav_mags/ folder

# load packages
module load metabat/2.13

# print the versions - useful for papers
metabat

# Summarize the contig depths using the jgi_summarize_bam_contig_depths tool from metabat2 which takes a sorted bam file as input.

#for bamfile in ./output/bwa_mem/setExtra/*_map/*.bam
#do
#    CORAL=$(echo "$bamfile" | awk -F'/' '{split($5, a, "_"); print a[1]}')
#    mkdir ./output/binning/setExtra/${CORAL}_bins
#    jgi_summarize_bam_contig_depths --outputDepth ./output/binning/setExtra/${CORAL}_bins/sample_depth.txt \
#        ${bamfile}
#done

# Run the binning algortithm using the assembly, depth file, and running over 5 threads. Previx of output bins is CORALID_bin

#for assembly in ./output/bwa_index/setExtra/*_assembly/final.contigs.fa
##do
 #   CORAL=$(echo "$assembly" | awk -F'/' '{split($5, a, "_"); print a[1]}')
 #   metabat2 -i ${assembly} \
 #       -o ./output/binning/setExtra/${CORAL}_bins/${CORAL}_bin \
#        -a ./output/binning/setExtra/${CORAL}_bins/sample_depth.txt \
##        -t 5
#done

########################################
###### METABAT2 FOR CO-ASSEMBLY ########
########################################

# Summarize the contig depths using the jgi_summarize_bam_contig_depths tool from metabat2 which takes sorted bam files as input.

mkdir ./output/binning/coassembly_bins
cd ./output/binning/coassembly_bins

BAM_FOLDER="/blue/juliemeyer/cynthiabecker/ofav_mags/output/bwa_mem/coassembly_map"
COASSEMBLY=/blue/juliemeyer/share/coassembly_rrc_ofav/coassembly_FLK_OFAV/final.contigs.fa

jgi_summarize_bam_contig_depths --outputDepth sample_depth.txt ${BAM_FOLDER}/*.bam

metabat2 -i ${COASSEMBLY} \
    -o coassembly_FLK_bin \
    -a sample_depth.txt \
    -m 2000 \
    -t 20

#### PARAMETERS
# -o is base of file name for each bin
# -a is the sample depth file generated by jgi_summarize_bam_contig_dephts
# -m is the min contig size considered for binning. I relaxed the default of 2500 to see if I would get more bins
# -t is number of threads

# RUN CHECKM on bins

# load packages
module load checkm
checkm

# Check the quality of genome bins using the standard workflow. I am doing this over 5 threads, with the bins in the "binning/all_bins" folder and output stored in a newly created "checkm" folder within the all_bins folder

checkm lineage_wf -t 20 -x fa . ./checkm